### ISSUE TITLE
Too much memory

### ISSUE THREAD

**Issue by S144S** [idreamsi/u8g2-persian-reshaper#2]
سلام
ممنون بابت کد خوبتون
من این کد رو ریختم روی نانو و 81درصد حافظه فلش و 74 رم رو مصرف کرد
کاری نمیشه کرد این بهینه شه؟
عملا جا برای چیز دیگه ای نموند

**Comment by idreamsi** [comment]
سلام
کد شامل دو بخش هست
کتابخونه اصلی که توسط اون نوشته ها نمایش داده میشه
و 
همین مثالی که بنده طراحی کردم و توسط اون نوشته های فارسی پردازش میشه
همین دو در کنار هم باعث میشه حجم خروجی برنامه زیاد بشه

همچنین چون فونت هم به برنامه ضمیمه میشه همین باعث افزایش حجم برنامه خواهد شد
یک راه حل تبدیل فقط کاراکترهای مورد نیاز هنگام تبدیل فونت هست یعنی فقط کاراکترهای حروف فارسی در حین تبدیل فونت که مورد نیاز هست تبدیل بشه و سایر کاراکترهایی که نیازی بهشون نیست هنگام درست کردن فونت، تبدیل نشه که اینطوری حجم خروجی فونت کاهش پیدا می کنه 

[راهنمای تبدیل فونت](https://www.idreams.ir/%da%86%da%af%d9%88%d9%86%da%af%db%8c-%d8%b3%d8%a7%d8%ae%d8%aa-%d9%81%d9%88%d9%86%d8%aa-%d8%af%d9%84%d8%ae%d9%88%d8%a7%d9%87-%d8%a8%d8%b1%d8%a7%db%8c-%da%a9%d8%aa%d8%a7%d8%a8%d8%ae%d8%a7%d9%86%d9%87-u8/)

**Comment by DARIOF8** [comment]
سلام و خسته نباشید
من میخواستم این کد رو به زبان c استفاده کنم امکانش هست؟ میخوام روی یک میکروی atmega128 بریزم نمیخوام cpp اردوینو باشه میخوام c باشه با اتمل استودیو برم جلو . منتها دانش خاصی در زمینه تبدیل کد از cpp به c ندارم ممنون میشم کمک کنید

**Comment by idreamsi** [comment]
> سلام و خسته نباشید من میخواستم این کد رو به زبان c استفاده کنم امکانش هست؟ میخوام روی یک میکروی atmega128 بریزم نمیخوام cpp اردوینو باشه میخوام c باشه با اتمل استودیو برم جلو . منتها دانش خاصی در زمینه تبدیل کد از cpp به c ندارم ممنون میشم کمک کنید


سلام
اینجا رو چک کنید:
https://designer2013.blogsky.com/1395/04/26/post-165/%DA%A9%D8%AA%D8%A7%D8%A8%D8%AE%D8%A7%D9%86%D9%87-%D9%88-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%85%D9%88%D9%86%D9%87-%D8%B1%D8%A7%D9%87-%D8%A7%D9%86%D8%AF%D8%A7%D8%B2%DB%8C-%D8%A7%D9%84-%D8%B3%DB%8C-%D8%AF%DB%8C-SSD1306


از اینجا دانلود کنید
[SSD1306_LIB_3.zip](https://github.com/idreamsi/u8g2-persian-reshaper/files/11891466/SSD1306_LIB_3.zip)
